### ISSUE TITLE
I met an error when add plugin

### ISSUE THREAD

**Issue by narrowsnap** [ezartech/ezar-ionic2-sidemenu#2]
Error: Invalid Plugin! plugins/com.ezartech.ezar.videooverlay needs a valid package.json
when I run :   ionic cordova plugin add plugins/com.ezartech.ezar.videooverlay
I don't know how to solve it? 
Can anyone help me?

**Comment by mayoljonathan** [comment]
`ionic cordova plugin add com.ezartech.ezar.videooverlay`

**Comment by narrowsnap** [comment]
Thank you!

At 2017-07-23 22:40:01, "tsebvaan" <notifications@github.com> wrote:


ionic cordova plugin add com.ezartech.ezar.videooverlay

**Comment by ezartech** [comment]
Update: I've published Cordova 7 compatible versions of the ezAR plugins to npm, read more here https://ezartech.discussion.community/post/cant-add-plugins-with-cordova-7-0-1-8723093?pid=1297125496
